apiVersion: v1
kind: Pod
metadata: {{}}
spec:
  containers:
    - name: frontman
      image: "{FRONTMAN_IMAGE}"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      imagePullPolicy: IfNotPresent
      env:
        - name: FLASK_RUN_PORT
          value: '80'
      volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
