apiVersion: v1
kind: Pod
metadata: {{}}
spec:
  containers:
    - name: keeper
      image: "{EVAL_KEEPER}"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      imagePullPolicy: IfNotPresent
