apiVersion: v1
kind: Pod
metadata:
  annotations: {{}}
spec:
  containers:
    - name: runtime
      image: "{DIND_IMAGE}"
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: 127.0.0.1:2375
        - name: LOG_LEVEL
          value: debug
      imagePullPolicy: "{IMAGE_PULL_POLICY}"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - mountPath: /etc/podinfo
          name: podinfo
        - mountPath: /lib/modules
          name: kernel
  volumes:
    - name: docker-storage
      hostPath:
        path: /dev/shm/dind
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
    - name: kernel
      hostPah:
        path: /lib/modules
        type: Directory
