apiVersion: v1
kind: Pod
metadata:
  annotations: {{}}
spec:
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
