---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-env
data:
  ORCHESTRATOR_TYPE: kubernetes
  DIND_IMAGE: ghcr.io/hpcclab/live_service_migration/migration-dind:main
  PIND_IMAGE: ghcr.io/hpcclab/live_service_migration/migration-pind:main
  AMBASSADOR_IMAGE: ghcr.io/hpcclab/live_service_migration/migration-ambassador:main
  FRONTMAN_IMAGE: ghcr.io/hpcclab/live_service_migration/frontman:main
  IMAGE_PULL_POLICY: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-operator
  labels:
    app: migration-operator
  annotations:
    migration-bypass: 'True'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: migration-operator
  template:
    metadata:
      labels:
        app: migration-operator
      annotations:
        migration-bypass: 'True'
    spec:
      serviceAccountName: migration-coordinator
      containers:
        - name: operator
          image: ghcr.io/hpcclab/live_service_migration/migration-operator:main
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: migration-env
          startupProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-coordinator
  labels:
    app: migration-coordinator
  annotations:
    migration-bypass: 'True'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: migration-coordinator
  template:
    metadata:
      labels:
        app: migration-coordinator
      annotations:
        migration-bypass: 'True'
    spec:
      serviceAccountName: migration-coordinator
      containers:
        - name: coordinator
          image: ghcr.io/hpcclab/live_service_migration/migration-coordinator:main
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: migration-env
          startupProbe:
            httpGet:
              port: 5000
              path: /healthcheck
          livenessProbe:
            httpGet:
              port: 5000
              path: /healthcheck
---
apiVersion: v1
kind: Service
metadata:
  name: migration-coordinator
  labels:
    app: migration-coordinator
spec:
  type: NodePort
  selector:
    app: migration-coordinator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-interceptor
  labels:
    app: migration-interceptor
  annotations:
    migration-bypass: 'True'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: migration-interceptor
  template:
    metadata:
      labels:
        app: migration-interceptor
      annotations:
        migration-bypass: 'True'
    spec:
      serviceAccountName: migration-coordinator
      containers:
        - name: interceptor
          image: ghcr.io/hpcclab/live_service_migration/migration-interceptor:main
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: migration-env
          startupProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
---
apiVersion: v1
kind: Service
metadata:
  name: migration-interceptor
  labels:
    app: migration-interceptor
spec:
  type: NodePort
  selector:
    app: migration-interceptor
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-native-interface
  labels:
    app: migration-native-interface
  annotations:
    migration-bypass: 'True'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: migration-native-interface
  template:
    metadata:
      labels:
        app: migration-native-interface
      annotations:
        migration-bypass: 'True'
    spec:
      serviceAccountName: migration-coordinator
      containers:
        - name: interface
          image: ghcr.io/hpcclab/live_service_migration/migration-native-interface:main
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/kubelet/migration
              name: migration
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: migration-env
          startupProbe:
            httpGet:
              port: 8888
          livenessProbe:
            httpGet:
              port: 8888
      volumes:
        - name: migration
          hostPath:
            path: /var/lib/kubelet/migration
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: migration-native-interface-nodeport
  labels:
    app: migration-native-interface
spec:
  type: NodePort
  selector:
    app: migration-native-interface
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 22
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: migration-native-interface
  labels:
    app: migration-native-interface
spec:
  selector:
    app: migration-native-interface
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888