---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterkopfpeerings.kopf.dev
spec:
  scope: Cluster
  group: kopf.dev
  names:
    kind: ClusterKopfPeering
    plural: clusterkopfpeerings
    singular: clusterkopfpeering
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: kopf.dev/v1
kind: ClusterKopfPeering
metadata:
  name: migration-coordinator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-coordinator
secrets:
  - name: default-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-coordinator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get, create, delete]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces, services, pods, pods/status, pods/exec, pods/log, events, nodes]
    verbs: [ get, list, watch, update, patch, create, delete ]
  #  - apiGroups: [apps]
  #    resources: [deployments]
  #    verbs: [get, list, watch, patch, create, delete]
  #  - apiGroups: [ networking.k8s.io ]
  #    resources: [ ingresses ]
  #    verbs: [ get, list, watch, create, delete ]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: migration-coordinator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: migration-coordinator-role-cluster
subjects:
  - kind: ServiceAccount
    name: migration-coordinator
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-coordinator
  namespace: myproject
secrets:
  - name: default-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: migration-coordinator-rolebinding-cluster-myproject
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: migration-coordinator-role-cluster
subjects:
  - kind: ServiceAccount
    name: migration-coordinator
    namespace: myproject