apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    migration-migratable: enabled
#    migration-desired-state: ready
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
